# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-11-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('GD', 'Grapichs & Design'), ('C', 'C++ Programing'), ('MA', 'Maths'), ('WP', 'Web Programming'), ('AF', 'Accounting & Finance'), ('FD', 'Fashion & Design')], max_length=2),
        ),
    ]
